#!/bin/sh
if ./mst start 2>&1 /dev/null | grep -q 'No such file or directory'; then
	./mst stop
fi
./mlxfwmanager $* | awk '!/-W-/'
ret=$?
./mst stop > /dev/null 2>&1
if [ $ret -eq 0 -o $ret -eq 254 ] ; then 
    ./UpdRollBack
fi
exit $re