#!/bin/sh
if [ -f /usr/bin/minit ]; then
if ./mst start > /dev/null 2>&1 | grep -q 'No such file or directory'; then
	./mst stop
fi
	./mlxfwmanager $*
	ret=$?
	./mst stop &> /dev/null
else
	./mlxfwmanager $*
	ret=$?
fi 
exit $ret